db 2
Dazz1ee/fintech-java pull request #7
Opened 2023-10-18 15:20 UTC by Dazz1ee

2023-10-19 20:27 UTC, GordPavel requested changes

2023-10-19 20:27 UTC, GordPavel commented on fintech/src/main/java/foo/configurations/ApplicationRunnerConfig.java
> +            weatherApiService.saveWeather("Moscow");
у тебя же вроде это уже было в liquibase скриптах миграции

2023-10-19 20:27 UTC, GordPavel commented on fintech/src/main/java/foo/dao/WeatherDaoImp.java
>          weathers = new ArrayList<>();
потокобезопасные счетчики, но коллекция не потокобезопасная

2023-10-19 20:27 UTC, GordPavel commented on fintech/src/main/java/foo/dao/WeatherDaoJdbc.java
> +            throw new CustomSQLException(e);
каждый новый уникальный кейс ошибки – отдельный тип кастомного исключения. Не нужно все под одно грести

2023-10-19 20:27 UTC, GordPavel commented on fintech/src/main/java/foo/dao/WeatherDaoJdbc.java
> +            connection.setAutoCommit(true);
не понимаю, зачем возвращать обратно

2023-10-19 20:27 UTC, GordPavel commented on fintech/src/main/java/foo/dao/WeatherDaoJdbc.java
> +    public Long saveCityIfNotExists(Connection connection, Weather weather) throws SQLException {
почему тут нет транзакции?

2023-10-19 20:27 UTC, GordPavel commented on fintech/src/main/java/foo/dao/WeatherDaoJdbc.java
> +        try {
Повторяющийся код. Значит стоит вынести в отдельный метод

2023-10-19 20:27 UTC, GordPavel commented on fintech/src/main/java/foo/dao/WeatherDaoJdbc.java
> +                throw new CreateWeatherException();
а с транзакцией что?

2023-10-19 20:27 UTC, GordPavel commented on fintech/src/main/java/foo/dao/WeatherDaoJdbc.java
> +            connection.setTransactionIsolation(Connection.TRANSACTION_REPEATABLE_READ);
на чем основывался при выборе транзакций?

2023-10-19 20:27 UTC, GordPavel commented on fintech/src/main/java/foo/other/CustomUriBuilder.java
> +                .host("localhost")
эти значения должны быть параметризуемы из конфигов

2023-10-19 23:19 UTC, Dazz1ee commented on fintech/src/main/java/foo/configurations/ApplicationRunnerConfig.java
> +            weatherApiService.saveWeather("Moscow");
Это сохранение погоды с внешнего сервиса (Weather API) при запуске приложения (это первое задание из дз)

2023-10-19 23:20 UTC, Dazz1ee commented on fintech/src/main/java/foo/dao/WeatherDaoJdbc.java
> +            connection.setAutoCommit(true);
Я думал, что перед возвращением в пул потоков надо сбросить состояние, но сейчас посмотрел и увидел что hikari делает это сам. Ещё вопрос. Лучше самому откатывать транзакцию, либо можно доверится hikari ?

```Java
         try {
            if (isCommitStateDirty && !isAutoCommit) {
               delegate.rollback();
               LOGGER.debug("{} - Executed rollback on connection {} due to dirty commit state on close().", poolEntry.getPoolName(), delegate);
            }

            if (dirtyBits != 0) {
               poolEntry.resetConnectionState(this, dirtyBits);
            }

            delegate.clearWarnings();
         }
```

2023-10-19 23:21 UTC, Dazz1ee commented on fintech/src/main/java/foo/dao/WeatherDaoJdbc.java
> +    public Long saveCityIfNotExists(Connection connection, Weather weather) throws SQLException {
Этот блок кода повторялся и я его вынес в отдельный метод, т.е. он будет выполняться внутри уже существующей транзакции

2023-10-19 23:21 UTC, Dazz1ee commented on fintech/src/main/java/foo/dao/WeatherDaoJdbc.java
> +            connection.setTransactionIsolation(Connection.TRANSACTION_REPEATABLE_READ);
Repetable Read использовал, чтобы другие транзакции не могли обновить строки, например: тип или имя города.

2023-10-19 23:22 UTC, Dazz1ee commented on fintech/src/main/java/foo/other/CustomUriBuilder.java
> +                .host("localhost")
Т.е. надо сделать класс не абстрактным и добавить его в контекст, чтобы можно было заинжектить параметры ?

2023-10-23 08:05 UTC, GordPavel commented on fintech/src/main/java/foo/dao/WeatherDaoJdbc.java
> +            connection.setAutoCommit(true);
лучше самому

2023-10-23 08:06 UTC, GordPavel commented on fintech/src/main/java/foo/other/CustomUriBuilder.java
> +                .host("localhost")
делаешь класс бином и инжектишь в него Configuration Properties с нужными конфигами

2023-10-23 08:09 UTC, GordPavel approved these changes
LGTM

2023-10-23 08:09 UTC, GordPavel commented on fintech/src/main/java/foo/configurations/UriBuilderConfig.java
> +public class UriBuilderConfig {
лучше ConfigurationProperties

2023-10-23 08:09 UTC, GordPavel commented on fintech/src/main/resources/application-dev.yml
> +host: localhost
не очень понятные имена конфигов

2023-10-23 12:17 UTC, merged